### ISSUE TITLE
Move to æneria

### ISSUE THREAD

**Issue by hferee** [YunoHost-Apps/pilea_ynh#25]
Pliea's repository is archived, and has now moved to æneria:
https://gitlab.com/aeneria/aeneria-app

I guess we whould package this app for yunohost instead now?

**Comment by SimonMellerin** [comment]
yep that's next step after I merged testing branch, I'm gonna dot his

**Comment by stilobique** [comment]
Hi @SimonMellerin ; have any plan for the previous month about the aeneria migration ??

**Comment by SimonMellerin** [comment]
Hi,

Sorry I have not gave a lot of news recently.

For now, aeneria/pilea is a bit broken (see #29) I'm currently working on a new way to retrieve data from Enedis. I'm almost ready to release a new version of aeneria but I'm waiting informations and a contract from Enedis.

With this new version come some breaking changes. That's why, when I'll be ready, I'm not going to update pilea_ynh but release an new yunohost package (aeneria_ynh). 

I'm gonna write a bit of documentation in order to explain how to migrate from pilea to aeneria without data loss (don't worry It will be as simple as possible, I have recently added a import/export function to do so)

**Comment by stilobique** [comment]
Alright, great news. I'm stay patient and wait for your new package ;) . Thanks for your replie and work !

**Comment by SimonMellerin** [comment]
[æneria package](https://github.com/YunoHost-Apps/aeneria_ynh) is almost ready to be used, [it has been added to Yunohost apps list](https://github.com/YunoHost/apps/pull/1044).

I'm just waiting CI passes to remove the "Work in progress" message.

The package should appear soon in Yunohost apps catalog.
